# Generated by Django 6.0.2 on 2026-03-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные реквизиты')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.CharField(blank=True, max_length=20, verbose_name='Дата рождения')),
                ('hire_date', models.CharField(blank=True, max_length=20, verbose_name='Дата трудоустройства')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('salary', models.CharField(blank=True, max_length=50, verbose_name='Оклад')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
